###* This file is just for testing the API endpoints
###* To use it, you need to install the REST Client extension in VSCode

### Get all products
GET http://localhost:3000/products

### Get product by id
GET http://localhost:3000/products/12

### Get products by gender
GET http://localhost:3000/products?gender=women

### Get products by gender
GET http://localhost:3000/products?gender=men

### Get products by type and gender
GET http://localhost:3000/products?type=footwear&gender=men

### Get products by type and gender
GET http://localhost:3000/products?gender=women&type=footwear


### User registration
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "username": "rayoMakuin",
    "email": "rayomakuin2001@gmail.com",
    "password": "A1235678"
}

### User login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "rayoMakuin",
    "password": "A1235678"
}

### Invalid login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "rayoMakuin",
    "password": "A123567",
}