GET http://localhost:3000/
###
GET http://localhost:3000/products

### 
GET http://localhost:3000/products/12

###
GET http://localhost:3000/products?gender=women

###
GET http://localhost:3000/products?gender=men

### 
GET http://localhost:3000/products?type=footwear&gender=men

###
GET http://localhost:3000/products?gender=women&type=footwear
